--CREATE RESERVATION TABLE
CREATE TABLE public.reservation(
    res_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inventory_id integer NOT NULL,
    inventory_make character varying NOT NULL,
    inventory_model character varying NOT NULL,
    inventory_thumbnail character varying NOT NULL,
    inventory_price numeric(9, 0) NOT NULL,
    inventory_qty integer NOT NULL DEFAULT 1,
    CONSTRAINT reservation_key PRIMARY KEY(res_id)
);
--SET RELATIONSHIP public.account and public.reservation
ALTER TABLE IF EXISTS public.reservation
ADD CONSTRAINT fk_reservation_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
--SET RELATIONSHIP public.reservation and public.inventory
ALTER TABLE IF EXISTS public.reservation
ADD CONSTRAINT fk_reservation_inventory FOREIGN KEY (inventory_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;